<?php
/**
 * GoesJoomla template framework.
 *
 * Declares HTML code structure for desktop layout's default theme.
 *
 * @copyright	Copyright (C) 2012 Manh-Cuong Nguyen. All rights reserved.
 * @author		Manh-Cuong Nguyen <cuongnm@goesjoomla.com>
 * @license		Visit http://www.goesjoomla.com/licenses.html for details.
 * @link		http://www.goesjoomla.com/templates.html
 */

// No direct access.
defined('_JEXEC') or die;
?>
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $doc->language; ?>" lang="<?php echo $doc->language; ?>" dir="<?php echo $doc->direction; ?>">
<?php
echo "<head>\n".'<jdoc:include type="head" />'."</head>\n";

// Checks if there is any message queued.
$hasMessage = count(JFactory::getApplication()->getMessageQueue());

// Generates body tag's class attribute.
$class = array(
	'gj-' . $params->get('gj_desktop_width')         . '-width',
	'gj-' . $params->get('gj_typography_text_style') . '-text-style'
);
! $hasMessage                         OR $class[] = 'gj-has-message';
! $params->get('gj_demo_full_layout') OR $class[] = 'gj-full-layout-preview';
$class = implode(' ', $class);
?>
<body id="gj-desktop" class="<?php echo $class; ?>">
	<a id="gj-anchor-top" name="gj-anchor-top"></a>

	<div id="gj-page">
<?php
	if ($hasMessage) :
		JHtml::_('stylesheet', 'templates/'.$doc->template.'/css/plugins/message.css'); ?>
		<div id="gj-system-message-ground" class="transition-fx dimension">
			<div id="gj-system-message" class="clearfix gj-container">
				<div id="gj-system-message-inner">
					<div id="gj-system-message-pos">
						<jdoc:include type="message" />
					</div>
				</div>
				<div id="gj-system-message-button-ground" class="f-right">
					<div id="gj-system-message-button">
						<a title="<?php echo JText::_('TPL_GJ_TOGGLE_MESSAGE'); ?>" href="javascript:void(0)"><span><?php echo JText::_('TPL_GJ_TOGGLE_MESSAGE'); ?></span></a>
					</div>
				</div>
			</div>
		</div>
<?php
	endif;

	if ($status->hasHeaderBlock) : ?>
		<header id="gj-header-ground">
			<div id="gj-header" class="clearfix gj-container">
<?php
			if ($status->hasLogoPos) :
				$class = $status->hasPersonalizePos ? ' class="f-left gj-left-column"' : ''; ?>
				<div id="gj-logo-pos"<?php echo $class; ?>>
<?php
					GJTemplate::inject('logo'); ?>
				</div>
<?php
			endif;

			if ($status->hasPersonalizePos) :
				$class = $status->hasLogoPos ? ' class="f-right gj-wide-right-column"' : ''; ?>
				<div id="gj-personalize-pos"<?php echo $class; ?>>
<?php
					GJTemplate::inject('personalize'); ?>
				</div>
<?php
			endif;

			if ($status->hasMenuBlock) : ?>
				<div id="gj-menu-ground" class="clearfix">
<?php
				if ($status->hasMenuLeftPos) :
					$class = $status->hasMenuRightPos ? ' class="f-left gj-wide-left-column"' : ''; ?>
					<div id="gj-menu-left-pos"<?php echo $class; ?>>
<?php
						GJTemplate::inject('menu-left'); ?>
					</div>
<?php
				endif;

				if ($status->hasMenuRightPos) :
					$class = $status->hasMenuLeftPos ? ' class="f-right gj-right-column"' : ''; ?>
					<div id="gj-menu-right-pos"<?php echo $class; ?>>
<?php
						GJTemplate::inject('menu-right'); ?>
					</div>
<?php
				endif; ?>
				</div>
<?php
			endif; ?>
			</div>
		</header>
<?php
	endif;

	if ($status->hasContentTopBlock) : ?>
		<div id="gj-content-top-ground">
			<div id="gj-content-top" class="gj-container">
<?php
			if ($status->hasPromoBlock) : ?>
				<div id="gj-promo-ground" class="clearfix">
<?php
				if ($status->hasPromoLeftPos) :
					$class = '';
					if ($status->hasPromoPos)
					{
						$class = ' class="f-left gj-promo-left-column"';
					}
					elseif ($status->hasPromoRightPos)
					{
						$class = ' class="f-left gj-half-width-column"';
					} ?>
					<div id="gj-promo-left-pos"<?php echo $class; ?>>
<?php
						GJTemplate::inject('promo-left'); ?>
					</div>
<?php
				endif;

				if ($status->hasPromoPos) :
					$class = '';
					if ($status->hasPromoLeftPos AND $status->hasPromoRightPos)
					{
						$class = ' class="f-left gj-promo-center-column"';
					}
					elseif ($status->hasPromoLeftPos)
					{
						$class = ' class="f-right gj-wide-promo-right-column"';
					}
					elseif ($status->hasPromoRightPos)
					{
						$class = ' class="f-left gj-wide-promo-left-column"';
					} ?>
					<div id="gj-promo-pos"<?php echo $class; ?>>
<?php
						GJTemplate::inject('promo'); ?>
					</div>
<?php
				endif;

				if ($status->hasPromoRightPos) :
					$class = '';
					if ($status->hasPromoPos)
					{
						$class = ' class="f-right gj-promo-right-column"';
					}
					elseif ($status->hasPromoLeftPos)
					{
						$class = ' class="f-right gj-half-width-column"';
					} ?>
					<div id="gj-promo-right-pos"<?php echo $class; ?>>
<?php
						GJTemplate::inject('promo-right'); ?>
					</div>
<?php
				endif; ?>
					<script type="text/javascript">new $GJ.template.equalizeColumnHeight('gj-promo-ground', ['gj-promo-left-pos', 'gj-promo-pos', 'gj-promo-right-pos']);</script>
				</div>
<?php
			endif;

			if ($status->hasContentTopPos) : ?>
				<div id="gj-content-top-pos" class="clearfix split-<?php echo min(array(5, $status->hasContentTopPos)); ?>">
<?php
					GJTemplate::inject('content-top', 'GJModule', 'is-horizontal="1"'); ?>
				</div>
<?php
			endif; ?>
			</div>
		</div>
<?php
	endif;

	if ($status->hasContentBlock) : ?>
		<div id="gj-content-ground">
			<div id="gj-content" class="clearfix gj-container">
<?php
			if ($status->hasCenterBlock) :
				$class = '';
				if ($status->hasLeftPos AND $status->hasRightPos)
				{
					$class = ' class="f-left gj-center-column"';
				}
				elseif ($status->hasLeftPos)
				{
					$class = ' class="f-right gj-wide-right-column"';
				}
				elseif ($status->hasRightPos)
				{
					$class = ' class="f-left gj-wide-left-column"';
				} ?>
				<div id="gj-center-ground"<?php echo $class; ?>>
<?php
				if ($status->hasBodyBlock) :
					$class = '';
					if ($status->hasInnerLeftPos AND $status->hasInnerRightPos)
					{
						$class = ' f-left gj-inner-center-column';
					}
					elseif ($status->hasInnerLeftPos)
					{
						$class = ' f-right gj-wide-inner-right-column';
					}
					elseif ($status->hasInnerRightPos)
					{
						$class = ' f-left gj-wide-inner-left-column';
					} ?>
					<div id="gj-body-ground" class="clearfix<?php echo $class; ?>">
<?php
					if ($status->hasBreadcrumbsPos) : ?>
						<div id="gj-breadcrumbs-pos" class="f-left gj-spread-width-column">
<?php
							GJTemplate::inject('breadcrumbs'); ?>
						</div>
<?php
					endif;

					if ($status->hasUserTopPos) : ?>
						<div id="gj-user-top-pos" class="clearfix f-left gj-spread-width-column split-<?php echo min(array(5, $status->hasUserTopPos)); ?>">
<?php
							GJTemplate::inject('user-top', 'GJModule', 'is-horizontal="1"'); ?>
						</div>
<?php
					endif;

					if ($status->hasUser1Pos) :
						$class = $status->hasUser2Pos ? 'gj-half-width-column' : 'gj-spread-width-column'; ?>
						<div id="gj-user1-pos" class="f-left <?php echo $class; ?>">
<?php
							GJTemplate::inject('user1'); ?>
						</div>
<?php
					endif;

					if ($status->hasUser2Pos) :
						$class = $status->hasUser1Pos ? 'gj-half-width-column' : 'gj-spread-width-column'; ?>
						<div id="gj-user2-pos" class="f-left <?php echo $class; ?>">
<?php
							GJTemplate::inject('user2'); ?>
						</div>
<?php
					endif;

					if ($status->hasMainBodyTopPos) : ?>
						<div id="gj-main-body-top-pos" class="clearfix f-left gj-spread-width-column split-<?php echo min(array(5, $status->hasMainBodyTopPos)); ?>">
<?php
							GJTemplate::inject('main-body-top', 'GJModule', 'is-horizontal="1"'); ?>
						</div>
<?php
					endif;

					if ($status->hasMainBodyPos) : ?>
						<div id="gj-main-body-pos" class="f-left gj-spread-width-column">
<?php
							GJTemplate::inject('main-body'); ?>
						</div>
<?php
					endif;

					if ($status->hasMainBodyBottomPos) : ?>
						<div id="gj-main-body-bottom-pos" class="clearfix f-left gj-spread-width-column split-<?php echo min(array(5, $status->hasMainBodyBottomPos)); ?>">
<?php
							GJTemplate::inject('main-body-bottom', 'GJModule', 'is-horizontal="1"'); ?>
						</div>
<?php
					endif;

					if ($status->hasUser3Pos) :
						$class = $status->hasUser4Pos ? 'gj-half-width-column' : 'gj-spread-width-column'; ?>
						<div id="gj-user3-pos" class="f-left <?php echo $class; ?>">
<?php
							GJTemplate::inject('user3'); ?>
						</div>
<?php
					endif;

					if ($status->hasUser4Pos) :
						$class = $status->hasUser3Pos ? 'gj-half-width-column' : 'gj-spread-width-column'; ?>
						<div id="gj-user4-pos" class="f-left <?php echo $class; ?>">
<?php
							GJTemplate::inject('user4'); ?>
						</div>
<?php
					endif;

					if ($status->hasUserBottomPos) : ?>
						<div id="gj-user-bottom-pos" class="clearfix f-left gj-spread-width-column split-<?php echo min(array(5, $status->hasUserBottomPos)); ?>">
<?php
							GJTemplate::inject('user-bottom', 'GJModule', 'is-horizontal="1"'); ?>
						</div>
<?php
					endif;

					if ($status->hasBannerPos) : ?>
						<div id="gj-banner-pos" class="f-left gj-spread-width-column">
<?php
							GJTemplate::inject('banner'); ?>
						</div>
<?php
					endif; ?>
					</div>
<?php
				endif;

				if ($status->hasInnerLeftPos) :
					$class = '';
					if ($status->hasBodyBlock)
					{
						$class = ' class="f-left gj-inner-left-column"';
					}
					elseif ($status->hasInnerRightPos)
					{
						$class = ' class="f-left gj-half-width-column"';
					} ?>
					<div id="gj-inner-left-pos"<?php echo $class; ?>>
<?php
						GJTemplate::inject('inner-left'); ?>
					</div>
<?php
				endif;

				if ($status->hasInnerRightPos) :
					$class = '';
					if ($status->hasBodyBlock)
					{
						$class = ' class="f-right gj-inner-right-column"';
					}
					elseif ($status->hasInnerLeftPos)
					{
						$class = ' class="f-right gj-half-width-column"';
					} ?>
					<div id="gj-inner-right-pos"<?php echo $class; ?>>
<?php
						GJTemplate::inject('inner-right'); ?>
					</div>
<?php
				endif; ?>
				</div>
<?php
			endif;

			if ($status->hasLeftPos) :
				$class = '';
				if ($status->hasCenterBlock)
				{
					$class = ' class="f-left gj-left-column"';
				}
				elseif ($status->hasRightPos)
				{
					$class = ' class="f-left gj-half-width-column"';
				} ?>
				<div id="gj-left-pos"<?php echo $class; ?>>
<?php
					GJTemplate::inject('left'); ?>
				</div>
<?php
			endif;

			if ($status->hasRightPos) :
				$class = '';
				if ($status->hasCenterBlock)
				{
					$class = ' class="f-right gj-right-column"';
				}
				elseif ($status->hasLeftPos)
				{
					$class = ' class="f-right gj-half-width-column"';
				} ?>
				<div id="gj-right-pos"<?php echo $class; ?>>
<?php
					GJTemplate::inject('right'); ?>
				</div>
<?php
			endif; ?>
			</div>
		</div>
<?php
	endif;

	if ($status->hasContentBottomBlock) : ?>
		<div id="gj-content-bottom-ground">
			<div id="gj-content-bottom" class="gj-container">
<?php
			if ($status->hasContentBottomPos) : ?>
				<div id="gj-content-bottom-pos" class="clearfix split-<?php echo min(array(5, $status->hasContentBottomPos)); ?>">
<?php
					GJTemplate::inject('content-bottom', 'GJModule', 'is-horizontal="1"'); ?>
				</div>
<?php
			endif;

			if ($status->hasAdditionalBlock) :
				$count = 0;
				! $status->hasUser5Pos OR $count += 1;
				! $status->hasUser6Pos OR $count += 1;
				! $status->hasUser7Pos OR $count += 1; ?>
				<div id="gj-additional-ground" class="clearfix split-<?php echo $count; ?>">
<?php
				if ($status->hasUser5Pos) : ?>
					<div id="gj-user5-pos" class="column">
<?php
						GJTemplate::inject('user5'); ?>
					</div>
<?php
				endif;

				if ($status->hasUser6Pos) : ?>
					<div id="gj-user6-pos" class="column">
<?php
						GJTemplate::inject('user6'); ?>
					</div>
<?php
				endif;

				if ($status->hasUser7Pos) : ?>
					<div id="gj-user7-pos" class="column">
<?php
						GJTemplate::inject('user7'); ?>
					</div>
<?php
				endif; ?>
				</div>
<?php
			endif; ?>
			</div>
		</div>
<?php
	endif;

	if ($status->hasFixedBlock) : ?>
		<div id="gj-fixed-ground">
			<div id="gj-fixed">
<?php
			if ($status->hasFixedLeftTopPos) : ?>
				<div id="gj-fixed-left-top-pos">
<?php
					GJTemplate::inject('fixed-left-top'); ?>
				</div>
<?php
			endif;

			if ($status->hasFixedLeftMiddlePos) : ?>
				<div id="gj-fixed-left-middle-pos">
<?php
					GJTemplate::inject('fixed-left-middle'); ?>
				</div>
				<script type="text/javascript">new $GJ.template.initializeFixedPosition('left');</script>
<?php
			endif;

			if ($status->hasFixedLeftBottomPos) : ?>
				<div id="gj-fixed-left-bottom-pos">
<?php
					GJTemplate::inject('fixed-left-bottom'); ?>
				</div>
<?php
			endif;

			if ($status->hasFixedRightTopPos) : ?>
				<div id="gj-fixed-right-top-pos">
<?php
					GJTemplate::inject('fixed-right-top'); ?>
				</div>
<?php
			endif;

			if ($status->hasFixedRightMiddlePos) : ?>
				<div id="gj-fixed-right-middle-pos">
<?php
					GJTemplate::inject('fixed-right-middle'); ?>
				</div>
				<script type="text/javascript">new $GJ.template.initializeFixedPosition('right');</script>
<?php
			endif;

			if ($status->hasFixedRightBottomPos) : ?>
				<div id="gj-fixed-right-bottom-pos">
<?php
					GJTemplate::inject('fixed-right-bottom'); ?>
				</div>
<?php
			endif; ?>
			</div>
		</div>
<?php
	endif;

	if ($status->hasFooterBlock) : ?>
		<footer id="gj-footer-ground">
			<div id="gj-footer" class="clearfix gj-container">
<?php
			if ($status->hasFooterLeftPos) :
				$class = $status->hasFooterRightPos ? ' class="f-left gj-half-width-column"' : ''; ?>
				<div id="gj-footer-left-pos"<?php echo $class; ?>>
<?php
					GJTemplate::inject('footer-left'); ?>
				</div>
<?php
			endif;

			if ($status->hasFooterRightPos) :
				$class = $status->hasFooterLeftPos ? ' class="f-right gj-half-width-column"' : ''; ?>
				<div id="gj-footer-right-pos"<?php echo $class; ?>>
<?php
					GJTemplate::inject('footer-right'); ?>
				</div>
<?php
			endif; ?>
			</div>
		</footer>
<?php
	endif; ?>
	</div>
<?php
if ($status->hasDebugBlock) :
	echo "\n"; ?>
	<div id="gj-debug-ground">
		<div id="gj-debug" class="gj-container">
			<div id="gj-debug-pos">
<?php
				GJTemplate::inject('debug'); ?>
			</div>
		</div>
	</div>
<?php endif; ?>

	<a id="gj-go-to-top" class="transition-fx position" href="<?php echo $_SERVER['REQUEST_URI']; ?>#gj-anchor-top"><span><?php echo JText::_('TPL_GJ_GO_TO_TOP'); ?></span></a>

	<script type="text/javascript"><!-- // --><![CDATA[
		new $GJ.template.goToTop('gj-go-to-top');
<?php
	if ($hasMessage) : ?>
		new $GJ.template.systemMessage();
<?php
	endif;

	if ($params->get('gj_demo_full_layout')) : ?>
		(function() {
			var body = document.getElementById('gj-body-ground'),
			columns = [
				document.getElementById('gj-left-pos-preview'),
				document.getElementById('gj-inner-left-pos-preview'),
				document.getElementById('gj-inner-right-pos-preview'),
				document.getElementById('gj-right-pos-preview')
			];

			for (var i = 0; i < columns.length; i++) {
				if (body && columns[i]) {
					$GJ.el.setStyle(columns[i], 'height', (body.offsetHeight - 36) + 'px');
				}
			}
		})();
<?php
	endif; ?>
	// ]]></script>
</body>
</html>